### ISSUE TITLE
File Installation Location

### ISSUE THREAD

**Issue by nathanaelpearson** [sthierolf/netbox-custom-links#1]
HI,
Can you update the guide or confirm when there files should be installed/copied to for Netbox/LibreNMS integration?
Thank you

**Comment by sthierolf** [comment]
Hi, I'm installing those in **/var/www/cgi-bin/** on the NetBox server. I'm also adding a cgi-bin configuration into the apache web server including **ProxyPass** to avoid issues with NetBox and gunicorn.

I made a blog post about it at: [Netbox Custom Links for Snipe-IT and LibreNMS](https://www.thierolf.org/blog/2020/netbox-custom-links-for-snipe-it-and-librenms/)
